### ISSUE TITLE
To Do List

### ISSUE THREAD

**Issue by aspina7** [R4EPI/sitrep#70]
Everywhere: 
* [x] [Zhian] text size in plots doesnt respond to theme_set base_size from setup chunk; only when setting element_text in the plot itself. Need to adapt outbreak and survey templates accordingly.

* [x] ~~[Discussion] would be good to also output a document (beside the word) which summarises what datasets were used (and their file paths), starting cases, dropped cases where the output is. And maybe warnings/errors?~~ [moved to nice-to-haves pr]
* [x]  [Zhian] in tab_* functions, change the warning when dropping NAs to be "call. = FALSE" to the warning function - as descriptive is no longer a user-facing function. 
* [x] [Zhian] add a license to the repo? see https://github.com/R4EPI/sitrep/issues/44
* [x] [Kate/Neale / Alex / Zhian] decide if also want to show code for making implicit NAs out of explicit e.g. "Missing" chars to NA. So if you want to make "No answer" an implicit NA, you would use fct_recode(NULL = "No answer")
* [x] [Kate] update all sitrep::descriptive tables with groupers to use sitrep::rename_redundant and augment_redundant for renaming similar columns
* [x] ~~[Neale] Add chi-squared test and t.test examples to website (there is already an example of this in the vaccination survey)~~ [moved to https://github.com/R4EPI/R4EPIs-website/issues/19#issue-494502584 on website]
* [x] [Zhian/Alex] consider dropping sitrep::discreptive in favour of arsenal::tableby (dplyr compatible? simple enough syntax for beginners?) - decided against, syntax too dense
* [x] [Neale] Under "## Installing and loading required packages " add that can check where your packages are using .libPaths() and give link to wiki/training material. Currently only says: "Program Files/R/R-[version]/library" which wont always be the case (particularly on MSF computers). 
* [x] [Neale?] double check that case_when is doing what it should when NAs are involved. case_when doesnt leave NAs as NAs, need to add extra argument. see below:
```
x <- c(NA, "good", "bad")
dplyr::case_when(
  is.na(x)    ~ NA_character_,
  x == "good" ~ "YAY",
  x == "bad"  ~ "BOO!",
  TRUE        ~ "WAT"
)
#> [1] NA     "YAY"  "BOO!"
```
* [x] [Neale?] switch all factor stuff to forcats (swap recode_factor out) - cross reference with point under "surveys" - all of the factor cleaning needs a bit of a fix
* [x] [Neale] add to intro to templates that feedback is always welcome via github. a la https://github.com/R4EPI/sitrep/issues/33#issue-400251292
* [x] [Alex] check the ceramics package as a map tile solution. See spatial analysis issue. Package is not quite there yet, but may be in the future. 
* [x] [Alex] Clean up sitrep::univariate_analysis - lot of unecessary repeating. Also need to add stratified.

-------------------------------------------------------------------------------------------------

Surveys: 
* [x] [Alex] all surveys - fix factor cleaning according to neale examples from outbreak templates (neale may have already done this)
* [x] [Alex] mortality and nutrition: finalise reason_no_consent chunk once descriptive function is able to deal with multiple choice variables split over several columns  (requires new tab_linelist function)
* [x] [Alex] nutriton: add a weighted table by household if received soap or not  (requires fixing weighting below). 
* [x] [Alex/Zhian] Add option for cluster design to add_weights. Input the number of clusters (i.e. villages), then the number of households within those clusters and the numberof kids for each house (i.e.) ... TO BE DISCUSSED once hear back from statistician
* [x] [Alex] add examples of stratified design and analysis by region. 
* [x] [Alex] nutrition survey - confirm that weighted proportions are the same as generated by the anthro package see https://github.com/R4EPI/sitrep/issues/140
* [x] [Alex] Nutrition: updated dictionary to switch measles for programme penetrance variable (soap)
* [x] [Alex/Zhian] Fix surveys cleaning section factors (cause of death and no consent somehow in same cleaning step) - may just be for vaccination.  
* [x] [Alex/Zhian] Add replace NA explicit in factor cleaning for vaccination (from mortality) 
* [x] [Alex] Change mortality and vaccination to use surv_weight variable after change to the add_weight function output change!
* [x] [Zhian - discuss with alex] the chunk "descriptive_sampling_bias" throws an error if the age group variable has missings (because descriptive now returns a row with "missings") - and the population data frame obviously doesnt have that extra row .... so row numbers differ. Do we just add a comment??
* [x] [Alex] fix the cluster_hh_size chunk - counting number of houses definitely wrong. 
* [x] [Alex] add cluster to mortality survey (need to define in dict)
* [x] [Alex] add descriptive of non-consent reasons at the begining results where describe sample
* [x] [Alex] add a weighted table for reason not vaccinated (to vacc survey template)
* [x] [Alex] double check in all templates that using correct order for counter and stratifier variables (e.g. in vaccination - can't just swap to have age_group first in order to flip the table.... use the new transpose argument!
* [x] [Zhian] need to add design effect option to tabulate_survey (see example from epiet RAS case study)
* [x] [Zhian] tabulate_survey function when pretty=TRUE, returns % symbol as well as CI in each cell. It would be enough to just have the column heading showing % (95%CI), and then in the cell have e.g. 35 (21-90). This relevnt to all pretty merging functions...
* [x] [Zhian] tabulate_survey when stratified - possible to give option for row or col props, as well as of total?? (same as we do for the descriptive functin)

-------------------------------------------------------------------------------------------------

Extras: 
* [x] ~~[NICE TO HAVE] if have time then add in the options to add sample size calculations see https://github.com/R4EPI/sitrep/issues/5~~ [moved to nice to have pr]
* [x] ~~[NICE TO HAVE] Consider implementing a variation of the wordr package which allows us to put pagebreaks in. ~~ [moved to nice to have pr]
* [x] ~~[NICE TO HAVE] on all plots - make y axis numbering go to top of axis, this happens because of expand(c(0,0)~~ [moved to nice to have pr]
* [x] ~~[see: https://github.com/reconhub/incidence/issues/105] on epicurves - possible to add a 2 weekly moving average? - issue posted on recon. Long term issue case.~~[moved to nice to have pr]
* [x] [NICE TO HAVE] Consider adding example of creating age_categories grouping in months for under fives to generic template (added in cholera tempalte - copy paste if acceptable)
* [x] [NICE TO HAVE] add kates suggestion of removing previously infected cases from denom in consecutive epiweeks (So in theory this is methodologically correct if can actually confirm that those who were counted as cases were in fact confirmed to be from the disease in question. In practice – likely have many suspected cases therefor would not necessarily be removed from the at risk category. Therefor questionable) - decided against - rare use case. 
* [x] [NICE TO HAVE] Confirm if there is an existing way to have discrete categories in choropleth maps 
https://timogrossenbacher.ch/2019/04/bivariate-maps-with-ggplot2-and-sf/  Mense, just stick with what we have. 
* [x] [NICE TO HAVE] adjust fmt_count to have an option of removing proportions, and an option for specifying a different denom (from measles - but works just as well with count...) - count is fine stick with that. 
* [x] [NICE TO HAVE] switch from cowplot to patchwork when released on cran (https://github.com/thomasp85/patchwork)  - patchwork not being released any time soon. (hasnt been worked on in a while)
* [x] [NICE TO HAVE] Add non binary gender option to plot_age_pyramid, see https://github.com/R4EPI/sitrep/issues/102#issue-424875062

-------------------------------------------------------------------------------------------------

Outbreaks:
* [x] [ZHIAN] Fix cowplot alignment of epicurvs and ar/cfr, so that ticks are in the middle of bars
-------------------------------------------------------------------------------------------------

From measles: 
* [x]  No lab data in dictionary - add fake lab data with example of how to merge and create case def. (see generic outbreak template). Do all above commented out,- comment out other analyses stratified by case def (just leave in as an example)
* [x] in gen_data specify that only those who received vaccine have dose entered 
* [x] add an example to data cleaning section for setting dose to NA where vaccine not given. (commented out)
* [x] add a thing about showing how many NA in each variable (summary has that) - add a bit to drop rows with xzy missing or based on bla... just use dplyr filter
* [x] add an example of writing cleaned dataset to excel (or double check that we have it there)

-------------------------------------------------------------------------------------------------

* [x] [ZHIAN]  when creating the epiweek variable - define as a factor and then add all weeks between min and max as levels - so that dont have to fuck around in tables with zerocount weeks. 
* [x] [ZHIAN] consider option of add_totals for proportions function,- so it just sums the counts of res, then runs proportions function and bind_rows. If you look at what I did in the CFR section of the cholera template, having to bind_rows of an overall and a group specific CFR calculation is a bit long winded.... 
* [x] [ZHIAN] Consider adding counts(proportions%) to inline_fun. See cholera template inline code before `#### Demographics`
* [x] [ZHIAN] fmt_ci_df(ar) adds a % sign at the end ... but if its per 10,000 population we dont want a % sign as seen after attack_rate code chunk
* [x] [ZHIAN] Get rid of do(..) and change functions to NSE? goes back to [issue#48](https://github.com/R4EPI/sitrep/issues/48#issue-402188312)

-------------------------------------------------------------------------------------------------

* [x] [ZHIAN/ALEX] Try and make tables that are too big fit nicely in worddoc output (maybe shorten col names or merge categories....

-------------------------------------------------------------------------------------------------

* [x] [ALEX] add option to add a ceiling to age_group - e.g. to have the highest group in months end at 24months... (not be 24+)
* [x] [ALEX] update descriptive function with option to have percentage of total, rather than column specific. 
* [x]  [ALEX] Mapping section: consider changing the plotting of choropleths as categories rather than continuous... also make the points stuff better
* [x] [ALEX] make sure all the 95%CIs are merged in the document tables... (think is just mortality section left over)
* [x] [ALEX] add kates admissions/exits table in seperate tables

------------------------------------------------------------------------------------------------

* [x] [DONE? ZHIAN?] Consider adding an option to age_pyramid which returns proportions rather than counts; and option to remove NAs; Horizontal_lines does not seem to work either.... 
* [x] [DONE?] When library(excel.link), message about someone called daniela - supress messages...
* [x]  [DONE] on epicurves, when you use scale_x_date(date_breaks = "1 week") - the axis labels change to full dates, is it possible to keep it with the default 2013-W01 for example?
* [x] [DONE?] using fmt_ci_df function doesnt work if use the mergeCI function from props functions (e.g. attack_rate)
* [x] [DONE] Find a better way to reference lines/chunks (is there some kind of hyperlink function?), for "Introduction to this template" section - no solution really, just reference code chunk names

**Comment by zkamvar** [comment]
>  on epicurves, when you use scale_x_date(date_breaks = "1 week") - the axis labels change to full dates, is it possible to keep it with the default 2013-W01 for example?

For this one, I think the answer is: don't use `scale_x_date(date_breaks = "1 week")` since incidence should do this by default for weekly incidence.

**Comment by zkamvar** [comment]
>  When library(excel.link), message about someone called daniela - supress messages...

Interesting design.... [the author uses the package startup message as a sort of dedication page.](https://github.com/gdemin/excel.link/search?q=daniela&unscoped_q=daniela). 

The solution is `suppressPackageStartupMessages(library("excel.link"))`

**Comment by aspina7** [comment]
> > on epicurves, when you use scale_x_date(date_breaks = "1 week") - the axis labels change to full dates, is it possible to keep it with the default 2013-W01 for example?
> 
> For this one, I think the answer is: don't use `scale_x_date(date_breaks = "1 week")` since incidence should do this by default for weekly incidence.

mmmm dont think it did though - only put the axis labels every couple of weeks, or will it automatically add them all but just making them go slanted?

**Comment by zkamvar** [comment]
> mmmm dont think it did though - only put the axis labels every couple of weeks, or will it automatically add them all but just making them go slanted?

By default, it will only put labels at six points along the curve. That can be changed by setting  `n_breaks = nrow(<incidence object>)` in the plot function. I'll make a quick PR to fix it

**Comment by zkamvar** [comment]
>  on epicurves - possible to add a 2 weekly moving average?

I'm not exactly sure what this means... Does this mean that you want the epicurve on a bi-weekly basis or that you want to track data on a bi-weekly basis?

**Comment by zkamvar** [comment]
>     * Find a better way to reference lines/chunks (is there some kind of hyperlink function?), for "Introduction to this template" section

We've seen that referencing lines doesn't really work too well. Referencing chunks by name is the best way to go so far.

**Comment by zkamvar** [comment]
> Were we going to find a way around not using do(..)?

I believe the plan is to add a stratifying option to the proportion functions so that a lot of the boilerplate can go away.

**Comment by zkamvar** [comment]
> Consider adding an option to age_pyramid which returns proportions rather than counts; and option to remove NAs; Horizontal_lines does not seem to work either....

This is more than one point! 

 - [ ] Option to return proportions, so basically, each bar would scale to 100% of the total age category? I believe that's possible. 
 - [ ] Option to remove NAs seems worthwhile.
 - [ ] RE horizontal_lines: prove it.

**Comment by aspina7** [comment]
> > on epicurves - possible to add a 2 weekly moving average?
> 
> I'm not exactly sure what this means... Does this mean that you want the epicurve on a bi-weekly basis or that you want to track data on a bi-weekly basis?

you add a line on top of the bars for epicurves, for each week you take the x number of weeks before and x number of weeks after to calculate the average. Essentially just smooths out the epicurve - useful for when your surveillance/reporting coverage fluctuates by week. 

Can do it with rollapply in zoo package - but wonder if worth adding as an option to incidence package?

**Comment by aspina7** [comment]
> > Were we going to find a way around not using do(..)?
> 
> I believe the plan is to add a stratifying option to the proportion functions so that a lot of the boilerplate can go away.

you or me?

**Comment by zkamvar** [comment]
> > > on epicurves - possible to add a 2 weekly moving average?
> > 
> > 
> > I'm not exactly sure what this means... Does this mean that you want the epicurve on a bi-weekly basis or that you want to track data on a bi-weekly basis?
> 
> you add a line on top of the bars for epicurves, for each week you take the x number of weeks before and x number of weeks after to calculate the average. Essentially just smooths out the epicurve - useful for when your surveillance/reporting coverage fluctuates by week.
> 
> Can do it with rollapply in zoo package - but wonder if worth adding as an option to incidence package?

I think this is a reasonable request for the epicurve. It seems similar to the goals of https://github.com/reconhub/incidence/issues/75 and https://github.com/reconhub/incidence/issues/83

**Comment by zkamvar** [comment]
> > > Were we going to find a way around not using do(..)?
> > 
> > 
> > I believe the plan is to add a stratifying option to the proportion functions so that a lot of the boilerplate can go away.
> 
> you or me?

I could give it a stab

**Comment by zkamvar** [comment]
> * [ZHIAN] consider option of add_totals for proportions function,- so it just sums the counts of res, then runs proportions function and bind_rows. If you look at what I did in the CFR section of the cholera template, having to bind_rows of an overall and a group specific CFR calculation is a bit long winded....

I think this and getting rid of `do()` are intertwined....
